name: Server2-Angular POC-HomeServer2

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches:
      - main
    paths:
      - 'my-angular-app/**'   # Only run if files in Angular folder change
      - '.github/workflows/ci-cd-angular.yml'  # Also run if this workflow changes

jobs:
  build:
    runs-on: [self-hosted,server2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build folder if not exists
        shell: powershell
        run: |
          if (!(Test-Path "D:/build/AllAppsBuild/angpoc")) {
            New-Item -ItemType Directory -Force -Path "D:/build/AllAppsBuild/angpoc"
          }

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true

      - name: Install dependencies
        shell: powershell
        working-directory: ./my-angular-app
        run: npm ci

      - name: Build Angular App
        shell: powershell
        working-directory: ./my-angular-app
        run: npm run build -- --output-path "E:/BuildTest//AllAppsBuild/angpoc"

      - name: Verify build output
        shell: powershell
        run: |
          Write-Host "Contents of E:/BuildTest/AllAppsBuild/angpoc:"
          Get-ChildItem -Path "E:/BuildTest/AllAppsBuild/angpoc" -Recurse
