name: server2-dotnetfw

on:
  workflow_dispatch: # Manual trigger only
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'dotnetfw/**'

jobs:
  build:
    runs-on: [self-hosted, server2] # Use label if you set one during runner setup

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet Packages
        run: msbuild "FTPGitTest.csproj" /t:Restore
        working-directory: ./dotnetfw

      - name: Backup Existing Build
        run: |
          $sourcePath = "E:\BuildTest\AllAppsBuild\dotnetfw"
          $backupRoot = "E:\BuildTest\Backup\dotnetfw"
          $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
          $backupPath = Join-Path $backupRoot $timestamp
          
          if (Test-Path $sourcePath) {
              New-Item -ItemType Directory -Force -Path $backupPath | Out-Null
              Copy-Item -Path "$sourcePath\*" -Destination $backupPath -Recurse -Force
              Write-Host "Backup created at $backupPath"
          } else {
              Write-Host "No existing build found to backup."
          }

      - name: Build and Publish
        run: |
          msbuild "FTPGitTest.csproj" `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:PublishProfile=FolderProfile1 `
            /p:PublishDir=E:\BuildTest\AllAppsBuild\dotnetfw\
        working-directory: ./dotnetfw
